### ISSUE TITLE
After updating Docker 

### ISSUE THREAD

**Issue by Assisstant** [dotnet/eShop#157]
System.InvalidOperationException
  HResult=0x80131509
  Message=Configuration missing value for: IdentityUrl
  Source=eShop.ServiceDefaults
  StackTrace:
   at Microsoft.Extensions.Configuration.ConfigurationExtensions.GetRequiredValue(IConfiguration configuration, String name) in D:\Projects\eShop\src\eShop.ServiceDefaults\ConfigurationExtensions.cs:line 6
   at Extensions.AddAuthenticationServices(IHostApplicationBuilder builder) in D:\Projects\eShop\src\WebApp\Extensions\Extensions.cs:line 57
   at Extensions.AddApplicationServices(IHostApplicationBuilder builder) in D:\Projects\eShop\src\WebApp\Extensions\Extensions.cs:line 14
   at Program.<Main>$(String[] args) in D:\Projects\eShop\src\WebApp\Program.cs:line 7

**Comment by davidfowl** [comment]
Did you run the apphost project?

**Comment by Assisstant** [comment]
Thank you!

**Comment by Assisstant** [comment]
Yes, I did thank you very much.





Sent using https://www.zoho.com/mail/








---- On Thu, 11 Jan 2024 07:57:13 +0100 David Fowler ***@***.***> wrote ---





Did you run the apphost project?
