### ISSUE TITLE
Full rebuild of eshop solution fails on ClientApp

### ISSUE THREAD

**Issue by timheuer** [dotnet/eShop#486]
When doing a rebuild of the eShop.sln it pukes on rebuilding with the following:

```
System.IO.IOException: The process cannot access the file 'D:\GitHub\eshop\src\ClientApp\obj\Debug\net8.0-android\lp\156\jl\res\values-sr\values-sr.xml' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at Microsoft.Android.Build.Tasks.Files.HashFile(String filename, HashAlgorithm hashAlg) in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/Files.cs:line 438
   at Microsoft.Android.Build.Tasks.Files.HashFile(String filename) in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/Files.cs:line 432
   at Microsoft.Android.Build.Tasks.Files.HasStreamChanged(Stream source, String destination) in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/Files.cs:line 271
   at Microsoft.Android.Build.Tasks.Files.CopyIfStreamChanged(Stream stream, String destination) in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/Files.cs:line 161
   at Microsoft.Android.Build.Tasks.Files.ExtractAll(ZipArchive zip, String destination, Action`2 progressCallback, Func`2 modifyCallback, Func`2 deleteCallback, Func`2 skipCallback) in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/Files.cs:line 371
   at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Extract(IDictionary`2 jars, ICollection`1 resolvedResourceDirectories, ICollection`1 resolvedAssetDirectories, ICollection`1 resolvedEnvironments, ICollection`1 proguardConfigFiles)
   at Xamarin.Android.Tasks.ResolveLibraryProjectImports.RunTask()
   at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 25
```

<details>
<summary> Full output from Rebuild action </summary>

```
Rebuild started at 17:00...
Restored D:\GitHub\eshop\src\Catalog.API\Catalog.API.csproj (in 1.26 sec).
Restored D:\GitHub\eshop\src\PaymentProcessor\PaymentProcessor.csproj (in 1.35 sec).
Restored D:\GitHub\eshop\src\WebAppComponents\WebAppComponents.csproj (in 1.37 sec).
Restored D:\GitHub\eshop\src\eShop.ServiceDefaults\eShop.ServiceDefaults.csproj (in 1.38 sec).
Restored D:\GitHub\eshop\tests\Basket.UnitTests\Basket.UnitTests.csproj (in 1.43 sec).
Restored D:\GitHub\eshop\src\Ordering.API\Ordering.API.csproj (in 1.45 sec).
Restored D:\GitHub\eshop\src\eShop.AppHost\eShop.AppHost.csproj (in 1.48 sec).
Restored D:\GitHub\eshop\src\Ordering.Domain\Ordering.Domain.csproj (in 1.5 sec).
Restored D:\GitHub\eshop\src\Webhooks.API\Webhooks.API.csproj (in 1.51 sec).
Restored D:\GitHub\eshop\tests\Ordering.FunctionalTests\Ordering.FunctionalTests.csproj (in 1.56 sec).
Restored D:\GitHub\eshop\src\WebApp\WebApp.csproj (in 1.59 sec).
Restored D:\GitHub\eshop\src\EventBus\EventBus.csproj (in 1.6 sec).
Restored D:\GitHub\eshop\src\Ordering.Infrastructure\Ordering.Infrastructure.csproj (in 1.61 sec).
Restored D:\GitHub\eshop\tests\Ordering.UnitTests\Ordering.UnitTests.csproj (in 1.71 sec).
Restored D:\GitHub\eshop\src\Basket.API\Basket.API.csproj (in 1.72 sec).
Restored D:\GitHub\eshop\src\Identity.API\Identity.API.csproj (in 1.77 sec).
Restored D:\GitHub\eshop\src\OrderProcessor\OrderProcessor.csproj (in 1.78 sec).
Restored D:\GitHub\eshop\src\WebhookClient\WebhookClient.csproj (in 1.8 sec).
Restored D:\GitHub\eshop\tests\Catalog.FunctionalTests\Catalog.FunctionalTests.csproj (in 1.82 sec).
Restored D:\GitHub\eshop\src\EventBusRabbitMQ\EventBusRabbitMQ.csproj (in 1.84 sec).
Restored D:\GitHub\eshop\src\IntegrationEventLogEF\IntegrationEventLogEF.csproj (in 1.85 sec).
Restored D:\GitHub\eshop\src\Mobile.Bff.Shopping\Mobile.Bff.Shopping.csproj (in 1.86 sec).
Restored D:\GitHub\eshop\src\ClientApp\ClientApp.csproj (in 555 ms).
Restored D:\GitHub\eshop\src\HybridApp\HybridApp.csproj (in 2.28 sec).
1>------ Rebuild All started: Project: ClientApp, Configuration: Debug Any CPU ------
2>------ Rebuild All started: Project: WebAppComponents, Configuration: Debug Any CPU ------
3>------ Rebuild All started: Project: Ordering.Domain, Configuration: Debug Any CPU ------
4>------ Rebuild All started: Project: EventBus, Configuration: Debug Any CPU ------
5>------ Rebuild All started: Project: eShop.ServiceDefaults, Configuration: Debug Any CPU ------
Restored D:\GitHub\eshop\tests\ClientApp.UnitTests\ClientApp.UnitTests.csproj (in 2.3 sec).
3>Ordering.Domain -> D:\GitHub\eshop\src\Ordering.Domain\bin\Debug\net8.0\Ordering.Domain.dll
5>eShop.ServiceDefaults -> D:\GitHub\eshop\src\eShop.ServiceDefaults\bin\Debug\net8.0\eShop.ServiceDefaults.dll
6>------ Rebuild All started: Project: WebhookClient, Configuration: Debug Any CPU ------
7>------ Rebuild All started: Project: Mobile.Bff.Shopping, Configuration: Debug Any CPU ------
8>------ Rebuild All started: Project: Identity.API, Configuration: Debug Any CPU ------
4>EventBus -> D:\GitHub\eshop\src\EventBus\bin\Debug\net8.0\EventBus.dll
9>------ Rebuild All started: Project: IntegrationEventLogEF, Configuration: Debug Any CPU ------
10>------ Rebuild All started: Project: EventBusRabbitMQ, Configuration: Debug Any CPU ------
8>D:\GitHub\eshop\src\Identity.API\Identity.API.csproj : warning NU1902: Package 'Duende.IdentityServer' 7.0.5 has a known moderate severity vulnerability, https://github.com/advisories/GHSA-ff4q-64jc-gx98
8>
8>Restore operation started
9>IntegrationEventLogEF -> D:\GitHub\eshop\src\IntegrationEventLogEF\bin\Debug\net8.0\IntegrationEventLogEF.dll
11>------ Rebuild All started: Project: Ordering.Infrastructure, Configuration: Debug Any CPU ------
8>
8>4 libraries restored in 0.33 seconds
2>WebAppComponents -> D:\GitHub\eshop\src\WebAppComponents\bin\Debug\net8.0\WebAppComponents.dll
12>------ Rebuild All started: Project: HybridApp, Configuration: Debug Any CPU ------
6>WebhookClient -> D:\GitHub\eshop\src\WebhookClient\bin\Debug\net8.0\WebhookClient.dll
1>D:\GitHub\eshop\src\ClientApp\Services\Basket\BasketService.cs(1,23,1,39): error CS0234: The type or namespace name 'BasketGrpcClient' does not exist in the namespace 'eShop.ClientApp' (are you missing an assembly reference?)
1>D:\GitHub\eshop\src\ClientApp\Services\Basket\BasketService.cs(118,13,118,29): error CS0246: The type or namespace name 'BasketGrpcClient' could not be found (are you missing a using directive or an assembly reference?)
1>D:\GitHub\eshop\src\ClientApp\Services\Basket\BasketService.cs(18,13,18,29): error CS0246: The type or namespace name 'BasketGrpcClient' could not be found (are you missing a using directive or an assembly reference?)
1>Done building project "ClientApp.csproj" -- FAILED.
1>D:\GitHub\eshop\src\ClientApp\Services\Basket\BasketService.cs(1,23,1,39): error CS0234: The type or namespace name 'BasketGrpcClient' does not exist in the namespace 'eShop.ClientApp' (are you missing an assembly reference?)
1>D:\GitHub\eshop\src\ClientApp\Services\Basket\BasketService.cs(118,13,118,29): error CS0246: The type or namespace name 'BasketGrpcClient' could not be found (are you missing a using directive or an assembly reference?)
1>D:\GitHub\eshop\src\ClientApp\Services\Basket\BasketService.cs(18,13,18,29): error CS0246: The type or namespace name 'BasketGrpcClient' could not be found (are you missing a using directive or an assembly reference?)
10>EventBusRabbitMQ -> D:\GitHub\eshop\src\EventBusRabbitMQ\bin\Debug\net8.0\EventBusRabbitMQ.dll
1>Done building project "ClientApp.csproj" -- FAILED.
13>------ Rebuild All started: Project: Webhooks.API, Configuration: Debug Any CPU ------
14>------ Rebuild All started: Project: WebApp, Configuration: Debug Any CPU ------
15>------ Rebuild All started: Project: PaymentProcessor, Configuration: Debug Any CPU ------
16>------ Rebuild All started: Project: OrderProcessor, Configuration: Debug Any CPU ------
17>------ Rebuild All started: Project: Catalog.API, Configuration: Debug Any CPU ------
18>------ Rebuild All started: Project: Basket.API, Configuration: Debug Any CPU ------
11>Ordering.Infrastructure -> D:\GitHub\eshop\src\Ordering.Infrastructure\bin\Debug\net8.0\Ordering.Infrastructure.dll
1>D:\GitHub\eshop\src\ClientApp\Services\Basket\BasketService.cs(1,23,1,39): error CS0234: The type or namespace name 'BasketGrpcClient' does not exist in the namespace 'eShop.ClientApp' (are you missing an assembly reference?)
1>D:\GitHub\eshop\src\ClientApp\Services\Basket\BasketService.cs(118,13,118,29): error CS0246: The type or namespace name 'BasketGrpcClient' could not be found (are you missing a using directive or an assembly reference?)
1>D:\GitHub\eshop\src\ClientApp\Services\Basket\BasketService.cs(18,13,18,29): error CS0246: The type or namespace name 'BasketGrpcClient' could not be found (are you missing a using directive or an assembly reference?)
1>Done building project "ClientApp.csproj" -- FAILED.
19>------ Rebuild All started: Project: Ordering.API, Configuration: Debug Any CPU ------
7>Mobile.Bff.Shopping -> D:\GitHub\eshop\src\Mobile.Bff.Shopping\bin\Debug\net8.0\Mobile.Bff.Shopping.dll
16>OrderProcessor -> D:\GitHub\eshop\src\OrderProcessor\bin\Debug\net8.0\OrderProcessor.dll
15>PaymentProcessor -> D:\GitHub\eshop\src\PaymentProcessor\bin\Debug\net8.0\PaymentProcessor.dll
1>ClientApp -> D:\GitHub\eshop\src\ClientApp\bin\Debug\net8.0-ios\iossimulator-x64\ClientApp.dll
13>Webhooks.API -> D:\GitHub\eshop\src\Webhooks.API\bin\Debug\net8.0\Webhooks.API.dll
8>Identity.API -> D:\GitHub\eshop\src\Identity.API\bin\Debug\net8.0\Identity.API.dll
8>Done building project "Identity.API.csproj".
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.128\tools\Xamarin.Android.EmbeddedResource.targets(39,5): error XARLP7024: System.IO.IOException: The process cannot access the file 'D:\GitHub\eshop\src\ClientApp\obj\Debug\net8.0-android\lp\156\jl\res\values-sr\values-sr.xml' because it is being used by another process.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.128\tools\Xamarin.Android.EmbeddedResource.targets(39,5): error XARLP7024:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.128\tools\Xamarin.Android.EmbeddedResource.targets(39,5): error XARLP7024:    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.128\tools\Xamarin.Android.EmbeddedResource.targets(39,5): error XARLP7024:    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.128\tools\Xamarin.Android.EmbeddedResource.targets(39,5): error XARLP7024:    at Microsoft.Android.Build.Tasks.Files.HashFile(String filename, HashAlgorithm hashAlg) in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/Files.cs:line 438
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.128\tools\Xamarin.Android.EmbeddedResource.targets(39,5): error XARLP7024:    at Microsoft.Android.Build.Tasks.Files.HashFile(String filename) in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/Files.cs:line 432
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.128\tools\Xamarin.Android.EmbeddedResource.targets(39,5): error XARLP7024:    at Microsoft.Android.Build.Tasks.Files.HasStreamChanged(Stream source, String destination) in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/Files.cs:line 271
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.128\tools\Xamarin.Android.EmbeddedResource.targets(39,5): error XARLP7024:    at Microsoft.Android.Build.Tasks.Files.CopyIfStreamChanged(Stream stream, String destination) in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/Files.cs:line 161
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.128\tools\Xamarin.Android.EmbeddedResource.targets(39,5): error XARLP7024:    at Microsoft.Android.Build.Tasks.Files.ExtractAll(ZipArchive zip, String destination, Action`2 progressCallback, Func`2 modifyCallback, Func`2 deleteCallback, Func`2 skipCallback) in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/Files.cs:line 371
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.128\tools\Xamarin.Android.EmbeddedResource.targets(39,5): error XARLP7024:    at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Extract(IDictionary`2 jars, ICollection`1 resolvedResourceDirectories, ICollection`1 resolvedAssetDirectories, ICollection`1 resolvedEnvironments, ICollection`1 proguardConfigFiles)
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.128\tools\Xamarin.Android.EmbeddedResource.targets(39,5): error XARLP7024:    at Xamarin.Android.Tasks.ResolveLibraryProjectImports.RunTask()
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.0.128\tools\Xamarin.Android.EmbeddedResource.targets(39,5): error XARLP7024:    at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 25
1>Done building project "ClientApp.csproj" -- FAILED.
20>------ Rebuild All started: Project: ClientApp.UnitTests, Configuration: Debug Any CPU ------
12>HybridApp -> D:\GitHub\eshop\src\HybridApp\bin\Debug\net8.0-ios\iossimulator-x64\HybridApp.dll
20>CSC : error CS0006: Metadata file 'D:\GitHub\eshop\src\ClientApp\obj\Debug\net8.0\ref\ClientApp.dll' could not be found
20>Done building project "ClientApp.UnitTests.csproj" -- FAILED.
12>HybridApp -> D:\GitHub\eshop\src\HybridApp\bin\Debug\net8.0-maccatalyst\maccatalyst-x64\HybridApp.dll
19>Ordering.API -> D:\GitHub\eshop\src\Ordering.API\bin\Debug\net8.0\Ordering.API.dll
21>------ Rebuild All started: Project: Ordering.UnitTests, Configuration: Debug Any CPU ------
22>------ Rebuild All started: Project: Ordering.FunctionalTests, Configuration: Debug Any CPU ------
18>Basket.API -> D:\GitHub\eshop\src\Basket.API\bin\Debug\net8.0\Basket.API.dll
23>------ Rebuild All started: Project: Basket.UnitTests, Configuration: Debug Any CPU ------
23>Basket.UnitTests -> D:\GitHub\eshop\tests\Basket.UnitTests\bin\Debug\net8.0\Basket.UnitTests.dll
21>Ordering.UnitTests -> D:\GitHub\eshop\tests\Ordering.UnitTests\bin\Debug\net8.0\Ordering.UnitTests.dll
22>Ordering.FunctionalTests -> D:\GitHub\eshop\tests\Ordering.FunctionalTests\bin\Debug\net8.0\Ordering.FunctionalTests.dll
14>WebApp -> D:\GitHub\eshop\src\WebApp\bin\Debug\net8.0\WebApp.dll
12>HybridApp -> D:\GitHub\eshop\src\HybridApp\bin\Debug\net8.0-android\HybridApp.dll
17>Catalog.API -> D:\GitHub\eshop\src\Catalog.API\bin\Debug\net8.0\Catalog.API.dll
24>------ Rebuild All started: Project: Catalog.FunctionalTests, Configuration: Debug Any CPU ------
25>------ Rebuild All started: Project: eShop.AppHost, Configuration: Debug Any CPU ------
12>HybridApp -> D:\GitHub\eshop\src\HybridApp\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\HybridApp.dll
24>Catalog.FunctionalTests -> D:\GitHub\eshop\tests\Catalog.FunctionalTests\bin\Debug\net8.0\Catalog.FunctionalTests.dll
25>eShop.AppHost -> D:\GitHub\eshop\src\eShop.AppHost\bin\Debug\net8.0\eShop.AppHost.dll
WARNING: Potential build performance issue in 'HybridApp.csproj'. The project does not appear up-to-date after a successful build: Input 'D:\GitHub\eshop\Directory.Build.props' is newer (2024-08-05 14:00:09.623) than earliest output 'D:\GitHub\eshop\src\HybridApp\obj\Debug\net8.0-android\scopedcss\bundle\HybridApp.styles.css' (2024-08-05 13:57:51.113), not up-to-date. See https://aka.ms/incremental-build-failure.
========== Rebuild All: 23 succeeded, 2 failed, 0 skipped ==========
========== Rebuild completed at 17:01 and took 01:16.563 minutes ==========
```

</details>

<details>
<summary>dotnet info</summary>

```
.NET SDK:
 Version:           8.0.400-preview.0.24324.5
 Commit:            736a2616db
 Workload version:  8.0.400-manifests.6ed602cb
 MSBuild version:   17.11.0+1192b22fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22635
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.400-preview.0.24324.5\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [android]
   Installation Source: SDK 8.0.400-preview.0, VS 17.12.35204.33
   Manifest Version:    34.0.128/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.android\34.0.128\WorkloadManifest.json
   Install Type:        FileBased

 [aspire]
   Installation Source: SDK 8.0.400-preview.0, VS 17.12.35204.33
   Manifest Version:    8.1.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.1.0\WorkloadManifest.json
   Install Type:        FileBased

 [ios]
   Installation Source: SDK 8.0.400-preview.0, VS 17.12.35204.33
   Manifest Version:    17.5.8017/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.ios\17.5.8017\WorkloadManifest.json
   Install Type:        FileBased

 [maccatalyst]
   Installation Source: SDK 8.0.400-preview.0, VS 17.12.35204.33
   Manifest Version:    17.5.8017/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maccatalyst\17.5.8017\WorkloadManifest.json
   Install Type:        FileBased

 [maui-windows]
   Installation Source: SDK 8.0.400-preview.0, VS 17.12.35204.33
   Manifest Version:    8.0.71/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.71\WorkloadManifest.json
   Install Type:        FileBased


Host:
  Version:      9.0.0-preview.6.24327.7
  Architecture: x64
  Commit:       static

.NET SDKs installed:
  8.0.400-preview.0.24324.5 [C:\Program Files\dotnet\sdk]
  9.0.100-preview.6.24328.19 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0-preview.6.24328.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0-preview.6.24327.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.0-preview.6.24327.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  D:\GitHub\eshop\global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

</details>

<details>
<summary>dotnet workload list</summary>

```
Installed Workload Id      Manifest Version       Installation Source
------------------------------------------------------------------------------------------
android                    34.0.128/8.0.100       SDK 8.0.400-preview.0, VS 17.12.35204.33
aspire                     8.1.0/8.0.100          SDK 8.0.400-preview.0, VS 17.12.35204.33
ios                        17.5.8017/8.0.100      SDK 8.0.400-preview.0, VS 17.12.35204.33
maccatalyst                17.5.8017/8.0.100      SDK 8.0.400-preview.0, VS 17.12.35204.33
maui-windows               8.0.71/8.0.100         SDK 8.0.400-preview.0, VS 17.12.35204.33

Use `dotnet workload search` to find additional workloads to install.

Updates are available for the following workload(s): ios maccatalyst. Run `dotnet workload update` to get the latest.
```

</details>

**Comment by baskint** [comment]
Similar issue - fails with three errors:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	CS0246	The type or namespace name 'BasketGrpcClient' could not be found (are you missing a using directive or an assembly reference?)	ClientApp (net8.0), ClientApp (net8.0-android), ClientApp (net8.0-maccatalyst), ClientApp (net8.0-windows10.0.19041.0)	S:\src\eShop\src\ClientApp\Services\Basket\BasketService.cs	18	
Error (active)	CS0246	The type or namespace name 'BasketGrpcClient' could not be found (are you missing a using directive or an assembly reference?)	ClientApp (net8.0), ClientApp (net8.0-android), ClientApp (net8.0-maccatalyst), ClientApp (net8.0-windows10.0.19041.0)	S:\src\eShop\src\ClientApp\Services\Basket\BasketService.cs	118	
Error (active)	CS0234	The type or namespace name 'BasketGrpcClient' does not exist in the namespace 'eShop.ClientApp' (are you missing an assembly reference?)	ClientApp (net8.0), ClientApp (net8.0-android), ClientApp (net8.0-maccatalyst), ClientApp (net8.0-windows10.0.19041.0)	S:\src\eShop\src\ClientApp\Services\Basket\BasketService.cs	1	
```

**Comment by ericwood8** [comment]
Similar

**Comment by jamesmontemagno** [comment]
You will need to generate BasketGrpcClient by opening the full eShop.sln

**Comment by jamesmontemagno** [comment]
BasketGrpcClient is auto generated whey you build the project. So you will get an error before building

**Comment by jamesmontemagno** [comment]
@jonathanpeppers is this android thing? fixed up?

**Comment by jonathanpeppers** [comment]
No, there is unfortunately a problem that started happening with recent versions of VS:
* Design-time build runs
* Developer clicks any of Clean, Rebuild, Build at the same time
* `IOException` or `UnauthorizedAccessException`

The only fix we've gotten from the project system team, is to try to not write files during a design-time build. This unfortunately, is a large rewrite of Android's design-time build -- so probably .NET 10 will be the first place we could get it complete.

But we can track this here instead:
* https://github.com/dotnet/android/issues/9133

**Comment by autoprog** [comment]
hi,


Open andcompiler solution ok

![Image](https://github.com/user-attachments/assets/7c54c13a-d15e-4120-9464-45c924ab668c)

Debug USB ok
![Image](https://github.com/user-attachments/assets/fcc859b2-2070-40ce-a1f0-67e32b0f497a)

new compiling... error

![Image](https://github.com/user-attachments/assets/d7935fe8-2f00-4686-8d56-e6e64e06b075)

Antevirus Off.

thanks.
Carlos.
