### ISSUE TITLE
The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by snps-steve** [dotnet/eShop#530]
I'm trying to get the app running locally on my local Windows machine. 

I believe the biggest SSL cert problem I'm having is related to this error: "---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: UntrustedRoot".

I don't see that this issue has been reported but I didn't do an extensive or exhaustive search.

Here's a more complete stack trace:

The SSL connection could not be established, see inner exception. AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: UntrustedRoot", DebugException="System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.")
       ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
       ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: UntrustedRoot
         at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
         at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
         at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(QueueItem queueItem)
         at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at Grpc.Net.Client.Balancer.Internal.BalancerHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)
         --- End of inner exception stack trace ---
         at Grpc.Net.Client.Internal.Retry.RetryCallBase`2.GetResponseCoreAsync()
         at Aspire.Dashboard.Model.DashboardClient.<>c__DisplayClass27_0.<<EnsureInitialized>g__ConnectAsync|2>d.MoveNext() in /_/src/Aspire.Dashboard/ResourceService/DashboardClient.cs:line 252
      --- End of stack trace from previous location ---
         at Aspire.Dashboard.Components.ApplicationName.OnInitializedAsync() in /_/src/Aspire.Dashboard/Components/Controls/ApplicationName.razor.cs:line 32
         at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**Comment by nicholasyin** [comment]
Yep, running the 'trust certificate' command doesn't work. It still complains about untrusted certificate.

**Comment by snps-steve** [comment]
I wound up setting up a subdomain, installing Nginx, and an SSL certificate from Let's Encrypt. I wasn't able to get it to work with all of the microservices (like authentication) but I was able to accomplish the testing that I needed.

**Comment by nicholasyin** [comment]
> I wound up setting up a subdomain, installing Nginx, and an SSL certificate from Let's Encrypt. I wasn't able to get it to work with all of the microservices (like authentication) but I was able to accomplish the testing that I needed.

The team probably never tested the code on a clean machine.

**Comment by TusharBeniwalGH** [comment]
refer link =https://learn.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-9.0&tabs=visual-studio%2Clinux-sles#trust-the-aspnet-core-https-development-certificate-on-windows-and-macos to resolve mentioned issue

**Comment by prophet1906** [comment]
Thanks @TusharBeniwalGH. This helped me:
```
dotnet dev-certs https --clean
dotnet dev-certs https --trust
```

**Comment by IEvangelist** [comment]
Closing as an environment certificate-trust issue with a confirmed resolution. The steps in https://github.com/dotnet/eShop/issues/530#issuecomment-2765561471 — `dotnet dev-certs https --clean` followed by `dotnet dev-certs https --trust` — resolved the report for a later user. On the current setup, Aspire diagnostics report a trusted development certificate, all resources start healthy, and certificate-verifying requests to the HTTPS dashboard and storefront succeed without `UntrustedRoot` errors.

A current failure after certificate cleanup/trust should be reported with `aspire doctor` output and the applicable machine policy.
