### ISSUE TITLE
No service for type 'OpenAI.OpenAIClient' has been registered.

### ISSUE THREAD

**Issue by MaxMelcher** [dotnet/eShop#633]
Hi all, 

just cloned [10c3b4b](https://github.com/dotnet/eShop/commit/10c3b4b91347663c4bd84e3e94e8b0b0fd7dc914) and enabled OpenAI 
with bool useOpenAI = true and adding adding the Connection String to the appSettings.json.

![Image](https://github.com/user-attachments/assets/70da7fdf-71b9-4927-9f6d-adbe8133256b)

When I launch in VS or deploy with azd up I get the error that the OpenAI.OpenAIClient cannot be resolved. 

``
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Extensions.<>c__DisplayClass3_0.<AddAIServices>b__1(IServiceProvider sp) in G:\Git\eShop\src\WebApp\Extensions\Extensions.cs:line 116
   at Microsoft.Extensions.AI.ChatClientBuilder.Build(IServiceProvider services)
   at Extensions.AddAIServices(IHostApplicationBuilder builder) in G:\Git\eShop\src\WebApp\Extensions\Extensions.cs:line 116
   at Extensions.AddApplicationServices(IHostApplicationBuilder builder) in G:\Git\eShop\src\WebApp\Extensions\Extensions.cs:line 33
   at Program.<Main>$(String[] args) in G:\Git\eShop\src\WebApp\Program.cs:line 10
``

Whats missing? 

Thanks,
Max

**Comment by Serhiiiiko** [comment]
same problem

**Comment by IEvangelist** [comment]
Closing as superseded. This report targets the former `useOpenAI = true` path at commit `10c3b4b`, where WebApp directly resolved `OpenAIClient`. That path has been removed. Current eShop uses `UseFoundry=true`, Aspire-managed chat and embedding deployments, and `Microsoft.Extensions.AI`; the AppHost configuration tests pass, and the README documents that this replaces the prior direct OpenAI/Azure OpenAI setup.

Any current Foundry registration failure should be reported with the present commit and configuration.
