### ISSUE TITLE
[WebToolsE2E][Aspire] After running the eshop.web solution, some rabbitMQ error logs appeared in the structured logs: "Unexpected connection closure: AMQP close-reason."

### ISSUE THREAD

**Issue by v-sherryfan** [dotnet/eShop#66]
**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install VS 17.9 P1 from build [34309.102.d17.9]
3. Install latest 8.0 SDK: 8.0.100
4. Apply NuGet Feeds
5. Install Docker Desktop

**REPRO STEPS**

1. In the VS, clone the eShop repository and open eShop.Web.slnf
2. F5 / Ctrl-F5
3. There are some rabbitMQ error logs 'Unexpected connection closure: AMQP close-reason' in Structured Logs

**ACTUAL**
Unexpected connection closure: AMQP close-reason, initiated by Library, code=0, text='End of stream', classId=0, methodId=0, cause=System.IO.EndOfStreamException: Reached the end of the stream. Possible authentication failure.
   at RabbitMQ.Client.Impl.InboundFrame.ReadFrom(Stream reader, Byte[] frameHeaderBuffer, ArrayPool`1 pool, UInt32 maxMessageSize)
   at RabbitMQ.Client.Impl.SocketFrameHandler.ReadFrame()
   at RabbitMQ.Client.Framing.Impl.Connection.MainLoopIteration()
   at RabbitMQ.Client.Framing.Impl.Connection.MainLoop()
![image](https://github.com/dotnet/eShop/assets/71361488/4933d8ca-2c9d-4766-8d02-024a432d615e)

**EXPECTED**
There are no errors in Structured Logs.

**Comment by eerhardt** [comment]
This is the same issue that @karolz-ms discusses here: https://github.com/dotnet/eShop/issues/42#issuecomment-1797016309. The proxy allows the connection, and then closes it. The client library (rightfully) logs this as an error because it doesn't expect the connection to be closed right after it is opened.

**Comment by IEvangelist** [comment]
Closing as no longer reproducible and superseded by current Aspire orchestration. This was identified as the same early DCP proxy/readiness behavior discussed in #42. Current AppHost wiring waits for RabbitMQ before dependent services start and uses a persistent container lifetime (see `0c77e88`). On current `main`, `eventbus` reaches `Running`/`Healthy`, with no matching connection-closure, authentication-failure, or end-of-stream error in startup logs.

If this recurs with a current Aspire version, please open a new issue with the AppHost/CLI versions and RabbitMQ startup logs.
